name: OneNightCity
version: '${project.version}'
main: me.chaounne.onenightcity.OneNightCity
api-version: 1.19
authors: [ Chaounne ]
description: Une cité mais version beaucoup plus rapide
website: https://twitter.com/SsbShawn
commands:
  city:
    description: city
    usage: /city
    aliases: city
  bounty:
    description: bounty
    usage: /bounty <amount> <player>
    aliases: bounty